### ISSUE TITLE
Cannot find address when PulseAudio is run by systemd

### ISSUE THREAD

**Issue by JuanKman94** [stefano-m/lua-pulseaudio_dbus#10]
Hello, stefano

I'm trying to use your widget but I get the error: `Failed to introspect object 'org.PulseAudio1', XML data was nil`.
If I run `pulseaudio --start` from a TTY/terminal, this error doesn't occur. But my normal setup is:

```bash
$ systemctl --user enable pulseaudio
```

Systemd's command is `pulseaudio --daemonize=no`.
Do you have any idea I can get around this?

```bash
> lua -v
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> awesome --version
awesome v4.3-91-ga0731023 (Too long)
 • Compiled against Lua 5.3.5 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.6
 • LGI version: 0.9.2
> ls /usr/lib64/luarocks/rocks/pulseaudio_*/
/usr/lib64/luarocks/rocks/pulseaudio_dbus/:
0.12.0-1/

/usr/lib64/luarocks/rocks/pulseaudio_widget/:
0.5.0-1/
> ls /usr/lib64/luarocks/rocks/dbus_proxy/0.9.0-1/
```

**Comment by stefano-m** [comment]
Hi,

I had similar issues with pulseaudio and ended up masking the service and have X11 start it.

I'm not sure about what's going on with systemd, but the unit does not start the DBus service and as a result the widget can't work.

**Comment by JuanKman94** [comment]
Okay. Thanks, anyway
If I come across a fix to my setup, I'll let you know!

**Comment by unai-ndz** [comment]
This only happens for me if I haven't used sound since I started the computer and only once, so if I reload awesomewm after getting the error on startup it works.
This makes me think the first time the widget asks for the service dbus starts it but the widget doesn't know until the second time it runs.

Do this also happen for you or it doesn't work for you at all unless you start it manually?

**Comment by JuanKman94** [comment]
It only works **if** I start `pulseaudio` manually from a terminal, i.e., if it is started automatically by `systemd --user` (see systemd(1)), when a program required audio, the widget **cannot** find the dbus address.

If I start it from a terminal (as my uid) and then restart `awesomewm`, then it works fine, as you say
