### ISSUE TITLE
Failed to introspect object 'org.PulseAudio1'

### ISSUE THREAD

**Issue by alberdingk-thijm** [stefano-m/lua-pulseaudio_dbus#20]
Hello, I'm running this handy widget on Awesome 4.3 (running with Lua 5.3 and D-Bus support) in Void Linux, and I'm getting an error on startup when trying to use the widget, which states:

```
Error while loading the PulseAudio widget
/usr/share/lua/5.3/dbus_proxy/_proxy.lua:404: Failed to introspect object 'org.PulseAudio1'
error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.PulseAudio1 was not provided by any .service files
code: SERVICE_UNKNOWN
```

Here is the relevant part of my `$HOME/.config/awesome/rc.lua` that runs before the call to `local pulse = require("pulseaudio_widget")`:

```lua
-- If LuaRocks is installed, make sure that packages installed through it are
-- found (e.g. lgi). If LuaRocks is not installed, do nothing.
pcall(require, "luarocks.loader")

-- Standard awesome library
local gears = require("gears")
local awful = require("awful")
require("awful.autofocus")
-- Notification library
local naughty = require("naughty")

-- Widget and layout library
local wibox = require("wibox")
-- Theme handling library
local beautiful = require("beautiful")

-- Keys library
local keys = require("keys")

-- {{{ Error handling
-- Check if awesome encountered an error during startup and fell back to
-- another config (This code will only ever execute for the fallback config)
if awesome.startup_errors then
    naughty.notify({ preset = naughty.config.presets.critical,
                     title = "Oops, there were errors during startup!",
                     text = awesome.startup_errors })
end

-- Handle runtime errors after startup
do
    local in_error = false
    awesome.connect_signal("debug::error", function (err)
        -- Make sure we don't go into an endless error loop
        if in_error then return end
        in_error = true

        naughty.notify({ preset = naughty.config.presets.critical,
                         title = "Oops, an error happened!",
                         text = tostring(err) })
        in_error = false
    end)
end
-- }}}

-- {{{ Variable definitions
local config = gears.filesystem.get_configuration_dir()
-- Themes define colours, icons, font and wallpapers.
beautiful.init(config .. "themes/" .. "gtk/theme.lua")

-- Start autorun
awful.spawn.with_shell(config .. "autorun.sh")
```

As I'm on Void, I don't use systemd but instead runit, which I have configured to start the D-Bus service but not the Pulseaudio service.
`/etc/pulse/client.conf` has `autospawn = true` (there is no `$HOME/.config/pulse/client.conf`), and the widget works fine after calling `start-pulseaudio-x11` or any other pulseaudio command (e.g., pactl, pacmd, pavucontrol), but it would be great if the widget could somehow let pulseaudio itself know to spawn a daemon and let a client connect.

**Comment by stefano-m** [comment]
Hi! Happy to know that you'd think this widget would be useful to you... less happy about your issue.

As far as I can tell, it seems that pulseaudio has started without its dbus service. If I'm right, this has nothing to do with the widget.

You can check in a terminal with

``` shell
dbus-send --session --dest=org.freedesktop.DBus --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames \
| grep -i pulse
```

and you should see something like 

```
      string "org.pulseaudio.Server"
      string "org.PulseAudio1"
```

If that's not the case, you need to configure pulseaudio accordingly.

As the README suggests, pulseaudio needs to be configured to use dbus. 

You'd need the below in your configuration (e.g. `~/.config/pulse/default.pa`)

```
.ifexists module-dbus-protocol.so
load-module module-dbus-protocol
.endif
```

I hope that this would help you.

I'm happy to make the documentation clearer too in case you have suggestions in regard.

Thanks!

**Comment by alberdingk-thijm** [comment]
Thanks for the quick reply. I do have `load-module module-dbus-protocol` in my `default.pa`, and it does get loaded once I start pulseaudio.
It looks like the problem might have more to do with my setup, unless it would be possible for dbus to automatically spawn a pulseaudio daemon, rather than just checking for one that is running.

While I have `start-pulseaudio-x11` in my `xinitrc.d`, when awesome starts up (via `exec dbus-run-session awesome`), `dbus-send` makes no mention of pulseaudio and `pacmd stat` confirms that "no PulseAudio daemon running, or not running as session daemon". This suggests to me that the PulseAudio daemon that gets started in my `xinitrc.d` either terminates on idle before `lua-pulseaudio_dbus` becomes a client, or perhaps that the dbus session of awesome is separate from whatever session `start-pulseaudio-x11` is run in.

With respect to documentation, I think the only thing that could potentially be clearer here is that PulseAudio needs to already be running when the widget starts up: otherwise, everything you have is clear and detailed.

**Comment by stefano-m** [comment]
I'm not sure what else can be done on my end :thinking: 
I noticed that sometimes `pulseaudio` starts OK *but* it does not load the DBus server.

If you run `pulseaudio --check ; echo $?` and the result is `0`, it means that it's indeed running, but if you can't see pulseaudio in the output of `dbus-send` then it has not started the DBus service and there might be something odd going on with the pulseaudio config.

You could try to restart pulseaudio once you X session has started (something like `pulseaudio --kill` should do it) and then check whether the DBus service has started. If it's there, you can try to restart `awesome` with something like `awesome-client <<< 'awesome.restart()'` and at this point the widget should work. If you get there, you may be able to work backwards to some functioning configuration.

> With respect to documentation, I think the only thing that could potentially be clearer here is that PulseAudio needs to already be running when the widget starts up: otherwise, everything you have is clear and detailed.

Thanks for the feedback, I'll try and add this.

**Comment by alberdingk-thijm** [comment]
Hmm, yeah running `pulseaudio --check ; echo $?` returns `0` immediately after starting `awesome` but `dbus-send` is definitely not reporting the DBus service until I try starting `pulseaudio` again or running something else that uses `pulseaudio` like `pacmd`, `pactl` or `pavucontrol`, at which point I then can restart to get the widget to work.

I'll try looking at things on the pulseaudio end some more: I realize the DBus interface doesn't even look like it's recommended on their end anymore, so it might be some kind of weird interaction between the pulseaudio DBus interface and my DBus version. I'll close the issue now as it seems like the problem is on that end instead. Thanks for your help!

**Comment by stefano-m** [comment]
No problem! TBH I think that pulseaudio never touched their DBus API even though it's officially "internal".

I don't know how often they update their web page, but the latest changes on

https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/

are dated 2012 so I'm not too worried that about stability.

Thanks again and good luck with whatever solution you find!
