### ISSUE TITLE
Help with a PR adding support for streams

### ISSUE THREAD

**Issue by doronbehar** [stefano-m/lua-pulseaudio_dbus#3]
Hello again,

I'm trying to elevate this great Lua module by creating a PR that will enable better support for multiple sinks and sources, thus includes creating functions that will:
- Make the next sink the default sink ([`FallbackSink`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Core/#fallbacksink)).
- [`Move`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/#move) all [`playback_stream`s](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/) to the [`FallbackSink`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Core/#fallbacksink).
- Make the next source the default source ([`FallbackSource`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Core/#fallbacksource)).
- [`Move`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/#move) all [`record_stream`s](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/) to the [`FallbackSource`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Core/#fallbacksource).

I've successfully created functions which change and read the `FallbackSink` but I'm having trouble with [`Move`](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/#move). This is what I created so far:

```lua
--- Pulseaudio
-- [core server functionality](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/)
-- @type Stream
pulse.Stream = {}

--- Move the Stream to a different sink
-- @tparam string value device object path to move the stream to
function pulse.Stream:move(value)
  self:Set("org.PulseAudio.Core1.Stream",
           "Move",
           lgi.GLib.Variant("o", value))
  self.Volume = {signature="o", value=value}
end

--- Get the pulseaudio [stream object](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/Stream/)
-- @tparam lgi.Gio.DBusConnection connection DBus connection to the
-- pulseaudio server
-- @return the pulseaudio core object that allows you to access the
-- various sound devices
function pulse.get_stream(connection, streampath)
  local stream = proxy.Proxy:new(
    {
      bus=connection,
      name=nil, -- nil, because bus is *not* a message bus.
      path=streampath,
      interface="org.PulseAudio.Core1.Stream"
    }
  )

  _update_table(pulse.Stream, stream)

  return stream
end
```

When testing, after changing the `FallbackSink` and creating a stream object with `pulse.get_stream`, `pulse.Stream:move(core.FallbackSink)` doesn't work. Do you think it has to do something with `lgi.GLib.Variant`? I just have no idea from where to begin debugging this..

Any help or a clue would be greatly appreciated :)
Thanks.

**Comment by stefano-m** [comment]
Hi,

thanks for trying to make this work. Would you mind explaining what one could achieve by implementing streams please?

The pulseaudio documentation says that `Move` is a method, as such, it should be called directly on the `Stream` object proxy. Also, the method takes an object path, not a variant.

In fact, you should be able to call the `Move` method directly without wrapping it.

E.g.

```lua
stream = pulseaudio.get_stream(connection, stream_path)
result = stream:Move(sink_path)
```

I've done a quick check and if the path does not exist, `result` will be `nil`, otherwise it's an empty `table`. Also note that if you don't pass a valid object path you will get an exception like

```
GLib-CRITICAL **: g_variant_new_object_path: assertion 'g_variant_is_object_path (object_path)' failed
```

Please not that there is a simple test suite with the code that you should be able to run using `busted` (installable with `luarocks`). The suite uses the currently running pulseaudio, so it'd be better if you weren't using any audio device when you run it. I'd like to have a test case for the feature you want to introduce too.

One last thing. If you plan to implement more than one feature (as it seems it's the case), please submit separate PRs.

Thanks and hope that this helps.

**Comment by doronbehar** [comment]
First of all, Thanks! It worked. I'm so happy now :-]

Allow me to explain why I felt the need to add this feature.
I don't know if you have multiple sinks on your machine and/or you're using them. On my machine though, I have 2 of them (analog and HDMI) and I use both of them. After I started to use AwesomeWM and stopped using `GNOME`, I realised that I need to create a script to switch between those 2 sinks, that's because `pacmd set-default-sink` is not enough.<sup>1,2,3</sup>

I wanted to create a script similar to [this one](https://gist.github.com/3v1n0/ad3ad73e0bdd466d7f4a95b3aa376285) using PulseAudio's D-Bus API and integrating it with AwesomeWM using your great https://github.com/stefano-m/awesome-pulseaudio_widget seemed most natural to me.

[1]: https://unix.stackexchange.com/a/67398/135796
[2]: http://terokarvinen.com/2015/volume-control-with-pulseaudio-command-line-tools
[3]: https://askubuntu.com/a/72076

[Here's is the PR](https://github.com/stefano-m/lua-pulseaudio_dbus/pull/4).
I hope you'll like it and merge it :)

**Comment by stefano-m** [comment]
No worries, I'm happy that my suggestion worked.

Personally, I never use 2 sinks at the same time, I switch between them when e.g. I plug my laptop to an external HDMI monitor.

Thanks for PR #4 I will have a look and give feedback.

Closing this issue now.
